# Generated by Django 3.1a1 on 2020-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='programme_division',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
