# Generated by Django 3.1a1 on 2020-06-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200603_1750'),
        ('students', '0004_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='city',
        ),
        migrations.AddField(
            model_name='guardian',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='core.school'),
            preserve_default=False,
        ),
    ]
