# Generated by Django 3.1a1 on 2020-06-07 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200607_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guardian',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
