# Generated by Django 3.1a1 on 2020-06-12 07:40

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200603_1750'),
        ('students', '0013_auto_20200611_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to=students.models.student_image_file_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school'),
            preserve_default=False,
        ),
    ]
