# Generated by Django 3.1a1 on 2020-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200612_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='students.Guardian'),
        ),
    ]
