# Generated by Django 3.1a1 on 2020-06-13 08:33

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200612_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student_image_file_path),
        ),
    ]
