# Generated by Django 3.1 on 2020-08-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20200613_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='house',
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
