# Generated by Django 3.1 on 2020-08-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_house'),
        ('students', '0018_auto_20200814_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.house'),
        ),
    ]
