# Generated by Django 3.1 on 2020-08-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grade'),
        ('students', '0020_auto_20200814_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='other_names',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_id',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='last name', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
    ]
