# Generated by Django 3.1 on 2020-08-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_class_name'),
        ('students', '0022_auto_20200814_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.class'),
        ),
    ]
