# Generated by Django 3.1a1 on 2020-06-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200603_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='schools', to='core.Programme'),
        ),
    ]
