# Generated by Django 3.1 on 2020-08-15 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_programme_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='class',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
