# Generated by Django 3.1 on 2020-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200815_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='created',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='school',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], primary_key=True, serialize=False),
        ),
    ]
