# Generated by Django 3.1 on 2020-08-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200815_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default='SHS 1', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], primary_key=True, serialize=False),
        ),
    ]
