# Generated by Django 3.1 on 2020-08-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.school'),
            preserve_default=False,
        ),
    ]
